# Generated by Django 5.1 on 2024-09-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
