# Generated by Django 5.1 on 2024-09-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_is_active_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
