# Generated by Django 5.1.1 on 2024-09-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_appointment_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
